"use client";

import { useCallback, useEffect, useState } from "react";
import { DataTable, type Column } from "@/components/data-table/data-table";
import { RoomForm } from "@/components/forms/room-form";
import { ActionButton } from "@/components/ui/action-button";
import { Modal } from "@/components/ui/modal";
import { roomsService } from "@/services/rooms.service";
import type { Room } from "@/types/api";

export default function RoomsPage() {
  const [rows, setRows] = useState<Room[]>([]); const [name, setName] = useState(""); const [hostId, setHostId] = useState(""); const [page, setPage] = useState(1); const [lastPage, setLastPage] = useState(1); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState<Room | null>(null); const [confirmDelete, setConfirmDelete] = useState(false); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const result = await roomsService.list({ name, host_id: hostId ? Number(hostId) : undefined, page, limit: 10 }); setRows(result.data); setLastPage(result.meta.lastPage); } catch (err) { setNotice(err instanceof Error ? err.message : "Erro ao listar salas."); } finally { setLoading(false); } }, [name, hostId, page]);
  useEffect(() => { const timer = setTimeout(load, 300); return () => clearTimeout(timer); }, [load]);
  async function act(action: "join" | "leave", room: Room) { try { await roomsService[action](room.id); setNotice(action === "join" ? "Você entrou na sala." : "Você saiu da sala."); load(); } catch (err) { setNotice(err instanceof Error ? err.message : "Ação não concluída."); } }
  async function details(room: Room) { try { setSelected(await roomsService.get(room.id)); } catch (err) { setNotice(err instanceof Error ? err.message : "Sala não encontrada."); } }
  async function remove() { if (!selected) return; try { await roomsService.remove(selected.id); setConfirmDelete(false); setSelected(null); setNotice("Sala removida."); load(); } catch (err) { setNotice(err instanceof Error ? err.message : "Não foi possível remover."); } }
  const columns: Column<Room>[] = [{ key: "name", label: "Sala", render: (room) => <div><strong>{room.name}</strong><small className="cell-subtitle">ID #{room.id}</small></div> }, { key: "status", label: "Status", render: (room) => <span className={`badge badge-${room.status.toLowerCase()}`}>{room.status}</span> }, { key: "host", label: "Anfitrião", render: (room) => `#${room.hostId}` }, { key: "capacity", label: "Capacidade", render: (room) => `${room.users?.length ?? 0}/${room.maxUsers}` }];
  return <><header className="page-header"><div><span className="eyebrow">Lobby</span><h1>Salas de jogo</h1><p>Crie um lobby ou encontre onde seus amigos estão.</p></div></header><div className="split-layout"><RoomForm onCreated={() => { setNotice("Sala criada com sucesso."); load(); }} /><div>{notice && <div className="notice" onClick={() => setNotice("")}>{notice}<span>×</span></div>}<DataTable rows={rows} columns={columns} rowKey={(row) => row.id} loading={loading} emptyMessage="Nenhuma sala encontrada." page={page} lastPage={lastPage} onPageChange={setPage} filters={[{ key: "name", label: "Filtrar por nome", placeholder: "Nome da sala", value: name }, { key: "host", label: "Filtrar por anfitrião", placeholder: "ID do anfitrião", value: hostId }]} onFilterChange={(key, value) => { setPage(1); if (key === "name") setName(value); else setHostId(value.replace(/\D/g, "")); }} actions={(room) => <><ActionButton variant="ghost" onClick={() => details(room)}>Detalhes</ActionButton><ActionButton variant="secondary" onClick={() => act("join", room)}>Entrar</ActionButton><ActionButton variant="ghost" onClick={() => act("leave", room)}>Sair</ActionButton></>} /></div></div>
    {selected && !confirmDelete && <Modal title={selected.name} onClose={() => setSelected(null)}><dl className="details"><div><dt>Status</dt><dd>{selected.status}</dd></div><div><dt>Capacidade</dt><dd>{selected.users?.length ?? 0} de {selected.maxUsers}</dd></div><div><dt>Anfitrião</dt><dd>{selected.host?.name ?? `#${selected.hostId}`}</dd></div><div><dt>Participantes</dt><dd>{selected.users?.map((user) => user.name).join(", ") || "Nenhum"}</dd></div></dl><div className="modal-actions"><ActionButton variant="danger" onClick={() => setConfirmDelete(true)}>Excluir sala</ActionButton><ActionButton onClick={() => act("join", selected)}>Entrar</ActionButton></div></Modal>}{selected && confirmDelete && <Modal title="Excluir sala?" onClose={() => setConfirmDelete(false)}><div className="stack"><p>A sala <strong>{selected.name}</strong> será removida.</p><div className="modal-actions"><ActionButton variant="ghost" onClick={() => setConfirmDelete(false)}>Cancelar</ActionButton><ActionButton variant="danger" onClick={remove}>Excluir definitivamente</ActionButton></div></div></Modal>}</>;
}
