"use client";

import { useCallback, useEffect, useState } from "react";
import { DataTable, type Column } from "@/components/data-table/data-table";
import { ActionButton } from "@/components/ui/action-button";
import { Modal } from "@/components/ui/modal";
import { UserForm } from "@/components/forms/user-form";
import { usersService } from "@/services/users.service";
import type { User } from "@/types/api";

export default function UsersPage() {
  const [rows, setRows] = useState<User[]>([]); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [page, setPage] = useState(1); const [lastPage, setLastPage] = useState(1); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(false); const [modal, setModal] = useState<"create" | "view" | "edit" | "delete" | null>(null); const [selected, setSelected] = useState<User | null>(null); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); setLoadError(false); try { const result = await usersService.list({ name, email, page, limit: 10 }); setRows(result.data); setLastPage(result.meta.lastPage); } catch (err) { setLoadError(true); setNotice(err instanceof Error ? err.message : "Erro ao buscar usuários."); } finally { setLoading(false); } }, [name, email, page]);
  useEffect(() => { const timer = setTimeout(load, 300); return () => clearTimeout(timer); }, [load]);
  function open(kind: typeof modal, user?: User) { setSelected(user ?? null); setModal(kind); }
  async function remove() { if (!selected) return; await usersService.remove(selected.id); setModal(null); setNotice("Usuário excluído."); load(); }
  const columns: Column<User>[] = [{ key: "name", label: "Nome", render: (user) => <strong>{user.name}</strong> }, { key: "email", label: "E-mail", render: (user) => user.email }, { key: "role", label: "Perfil", render: (user) => <span className={`badge ${user.role === "ADMIN" ? "badge-purple" : ""}`}>{user.role}</span> }];
  return <><header className="page-header"><div><span className="eyebrow">Administração</span><h1>Usuários</h1><p>Consulte, filtre e mantenha as contas da plataforma.</p></div><ActionButton onClick={() => open("create")}>+ Novo usuário</ActionButton></header>{notice && <div className="notice" onClick={() => setNotice("")}>{notice}<span>×</span></div>}<DataTable rows={rows} columns={columns} rowKey={(row) => row.id} loading={loading} connected={!loadError} emptyMessage="Nenhum usuário encontrado." page={page} lastPage={lastPage} onPageChange={setPage} filters={[{ key: "name", label: "Filtrar por nome", placeholder: "Digite um nome", value: name }, { key: "email", label: "Filtrar por e-mail", placeholder: "nome@email.com", value: email }]} onFilterChange={(key, value) => { setPage(1); if (key === "name") setName(value); else setEmail(value); }} actions={(user) => <><ActionButton variant="ghost" onClick={() => open("view", user)}>Ver</ActionButton><ActionButton variant="secondary" onClick={() => open("edit", user)}>Editar</ActionButton><ActionButton variant="danger" onClick={() => open("delete", user)}>Excluir</ActionButton></>} />
    {modal === "create" && <Modal title="Novo usuário" onClose={() => setModal(null)}><UserForm onSaved={() => { setModal(null); load(); }} /></Modal>}{modal === "edit" && selected && <Modal title="Editar usuário" onClose={() => setModal(null)}><UserForm user={selected} onSaved={() => { setModal(null); load(); }} /></Modal>}{modal === "view" && selected && <Modal title="Detalhes do usuário" onClose={() => setModal(null)}><dl className="details"><div><dt>Nome</dt><dd>{selected.name}</dd></div><div><dt>E-mail</dt><dd>{selected.email}</dd></div><div><dt>Perfil</dt><dd>{selected.role}</dd></div><div><dt>ID</dt><dd>#{selected.id}</dd></div></dl></Modal>}{modal === "delete" && selected && <Modal title="Excluir usuário?" onClose={() => setModal(null)}><div className="stack"><p>Esta ação removerá <strong>{selected.name}</strong> permanentemente.</p><div className="modal-actions"><ActionButton variant="ghost" onClick={() => setModal(null)}>Cancelar</ActionButton><ActionButton variant="danger" onClick={remove}>Confirmar exclusão</ActionButton></div></div></Modal>}</>;
}
